### ISSUE TITLE
Error output from freebox_

### ISSUE THREAD

**Issue by Owned67** [architek/Munin-Plugin-Freebox#1]
Bonjour,

désoler de poster ici mais impossible d'ouvrir un ticket sur ton fork....

comment corriger cette erreur s'il te plaît :

2017/11/12-02:15:10 [700] Error output from freebox_:
2017/11/12-02:15:10 [700] Must be called freebox_{temp|bandwidth|freeplug|snr|fec|attn|switch1|switch2|switch3|switch4|uptime|multi}.
2017/11/12-02:15:10 [700] Service 'freebox_' exited with status 255/0.
2017/11/12-02:15:10 [700] Error output from freebox_:
2017/11/12-02:15:10 [700] Must be called freebox_{temp|bandwidth|freeplug|snr|fec|attn|switch1|switch2|switch3|switch4|uptime|multi}.
2017/11/12-02:15:10 [700] Service 'freebox_' exited with status 255/0.
2017/11/12-02:16:52 Server closing`

Les graphiques fonctionnent bien, c'est juste que ça me spam dans le log....

Pour te répondre :non je n'ai pas résolu le problème mais je vais essayer avec ta solution.

Merci

**Comment by architek** [comment]
Bonjour,

Veille à prendre la dernière version qui améliore le message d'erreur.

J'ai aussi mis à jour la documentation:
Il est préferable d'utiliser un lien freebox_multi et d'adapter dans le script la variable @multi en fonction de ce qu'on veut afficher. En mode multi, le plugin n'ouvrira qu'une seule connexion à la freebox pour récuperer en une fois toutes les données.

**Comment by Owned67** [comment]
Je te tiendrais au courant, je n'ai pas le temps pour le moment de trouver l'erreur lié à la freebox... Erreur d'authentification pourtant je n'ai rien modifié depuis et l'accès est toujours actif en regardant sur Freebox OS... Je ré-ouvrirais si besoin

**Comment by architek** [comment]
Si tu as mis à jour le plugin comme je te l'ai recommandé, c'est normal que tu ai une erreur d'authentification puisqu'elle dépend du nom de l'application que j'ai dû changer (pour être en ligne avec WWW::FBX), voir [e7bb9b4](https://github.com/architek/Munin-Plugin-Freebox/commit/e7bb9b44053a5bb5c756a58afca9cdfc5ba4b46f#diff-0e5663e1664e1cf57bea632fe037e354R94).
Il te suffit de relancer l'autoconf
`sudo munin-run --debug freebox_multi autoconf`
Et mettre à jour les 2 variables dans _/etc/munin/plugin-conf.d/munin-node_

Ton erreur initiale était peut-etre dû à une erreur de documentation combinée à une erreur de code qui laissait passer un mode interdit. C'est dorénavant corrigé et en cas d'erreur, le message est explicite. 
Au final, le plus simple est de n'avoir qu'un lien freebox_multi dans /etc/plugins/ et si nécessaire adapter la variable multi pour choisir les graphes que tu veux voir. Tu peux aussi adapter les couleurs si ca ne convient pas à ton thème.

Ok pour clore le ticket, n'hesites pas à en rouvrir un si tu as des questions ou tu trouves des erreurs de docs ou de code.

**Comment by Owned67** [comment]
ah ok... Merci de l'information. J'ai pas encore pu tester, couché depuis trois jours avec la grippe ^^

Merci pour tes réponses !

**Comment by Owned67** [comment]
Salut,

2018/01/13-03:15:08 [6529] Error output from freebox_:
2018/01/13-03:15:08 [6529] 	Plugin was called with /etc/munin/plugins/freebox_, must be called freebox_{fec|uptime|bandwidth|snr|up|down|attn|temp|switch1|switch2|switch3|switch4|multi}.
2018/01/13-03:15:08 [6529] Service 'freebox_' exited with status 255/0.
2018/01/13-03:15:08 [6529] Error output from freebox_:
2018/01/13-03:15:08 [6529] 	Plugin was called with /etc/munin/plugins/freebox_, must be called freebox_{fec|uptime|bandwidth|snr|up|down|attn|temp|switch1|switch2|switch3|switch4|multi}.
2018/01/13-03:15:08 [6529] Service 'freebox_' exited with status 255/0.
2018/01/13-03:15:10 [6529] Error output from freebox_multi:
2018/01/13-03:15:10 [6529] 	Erreur d'authentification de l'application at /usr/local/share/perl/5.24.1/WWW/FBX.pm line 123
2018/01/13-03:15:10 [6529] Service 'freebox_multi' exited with status 255/0.

**Comment by architek** [comment]
Salut,

L'erreur t'indique le problème. Tu as un lien qui s'appele freebox_ alors qu'il devrait s'appeler freebox_multi.

```
cd /etc/munin/plugins
mv freebox_ freebox_multi

```
Voici ce que je te conseillais dans ma réponse précedente:

As architek said:

> Au final, le plus simple est de n'avoir qu'un lien freebox_multi dans /etc/plugins/ et si nécessaire adapter la variable multi pour choisir les graphes que tu veux voir.

**Comment by Owned67** [comment]
comment n'avoir qu'un switch justement ?

L'erreur n'est plus, merci

**Comment by architek** [comment]
Tu edites cette ligne : https://github.com/architek/Munin-Plugin-Freebox/blob/master/freebox_#L106
Il y a quelques exemples au dessus pour les graphs disponible.
Mais attention, c'est la dernière ligne multi qui fait foi (la ligne 106 actuellement)

**Comment by Owned67** [comment]
Merci :) Joli le thème, c'est via le navigateur ou ?

**Comment by architek** [comment]
Non, c'est un thème côté serveur: [Hypfer/munstrap-dark](https://github.com/Hypfer/munstrap-dark).

**Comment by Owned67** [comment]
Merci
